# Uncomment the next line to define a global platform for your project
target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :ios, '13.0'
  source 'https://cdn.cocoapods.org/CocoaPods-version.yml'
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  
end